import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  LayoutDashboard, ClipboardList, WalletCards, CalendarDays, Tags, Users,
  LogOut, Search, Plus, Download, Eye, Pencil, Trash2, Check, X,
  Menu, UserCircle, KeyRound, ChevronDown, ChevronLeft, ChevronRight
} from 'lucide-react';
import logo from './assets/pitch-logo.png';
import './styles.css';

const seed = {
  applications: [
    { id:'PX-10248', applicant:'ABC Technologies', email:'hello@abctech.com', phone:'+91 98765 12001', type:'Raise Funds', event:'PitchXPO Conclave', amount:99, payment:'Paid', status:'New', date:'2026-08-18', note:'', documents:['Pitch Deck.pdf'] },
    { id:'PX-10247', applicant:'Nova Properties', email:'contact@novaproperties.com', phone:'+91 98765 12002', type:'Showcase', event:'PitchXPO Conclave', amount:99, payment:'Paid', status:'Reviewing', date:'2026-08-17', note:'Financial documents need review.', documents:['Company Profile.pdf'] },
    { id:'PX-10246', applicant:'Northstar Capital', email:'team@northstar.com', phone:'+91 98765 12003', type:'Investor Success Story', event:'PitchXPO Conclave', amount:299, payment:'Paid', status:'Approved', date:'2026-08-16', note:'Approved.', documents:['Success Story.pdf'] },
    { id:'PX-10245', applicant:'Vertex Labs', email:'founders@vertexlabs.com', phone:'+91 98765 12004', type:'Raise Funds', event:'PitchXPO Conclave', amount:99, payment:'Unpaid', status:'New', date:'2026-08-15', note:'', documents:['Pitch Deck.pdf'] },
    { id:'PX-10244', applicant:'Atlas Ventures', email:'team@atlas.com', phone:'+91 98765 12005', type:'Showcase', event:'Innovation Summit', amount:149, payment:'Paid', status:'Approved', date:'2026-08-14', note:'', documents:['Company Profile.pdf'] },
  ],
  payments: [
    {id:'PAY-9001', application:'PX-10248', applicant:'ABC Technologies', type:'Raise Funds', amount:99, status:'Paid', reference:'pi_8KAB1201', date:'2026-08-18'},
    {id:'PAY-9002', application:'PX-10247', applicant:'Nova Properties', type:'Showcase', amount:99, status:'Paid', reference:'pi_8KAB1202', date:'2026-08-17'},
    {id:'PAY-9003', application:'PX-10245', applicant:'Vertex Labs', type:'Raise Funds', amount:99, status:'Unpaid', reference:'—', date:'2026-08-15'},
    {id:'PAY-9004', application:'PX-10244', applicant:'Atlas Ventures', type:'Showcase', amount:149, status:'Paid', reference:'pi_8KAB1204', date:'2026-08-14'},
  ],
  events: [
    {id:'EV-001', name:'PitchXPO Conclave', from:'2026-09-18', to:'2026-09-20', venue:'Expo City', status:'Open'},
    {id:'EV-002', name:'Innovation Summit', from:'2026-10-09', to:'2026-10-11', venue:'Dubai World Trade Centre', status:'Open'},
  ],
  types: [
    {id:'TP-001', name:'Raise Funds', description:'For ventures seeking capital.', price:99, active:true},
    {id:'TP-002', name:'Showcase', description:'For founders showcasing products.', price:149, active:true},
    {id:'TP-003', name:'Investor Success Story', description:'Featured success stories.', price:299, active:true},
  ],
  users: [
    {id:'USR-001', name:'Admin User', email:'admin@pitchxpo.com', role:'Super Admin', status:'Active'},
    {id:'USR-002', name:'Sarah Khan', email:'sarah@pitchxpo.com', role:'Reviewer', status:'Active'},
  ],
  account: {name:'Admin User', email:'admin@pitchxpo.com', role:'Super Admin'}
};

const load = () => { try { return JSON.parse(localStorage.getItem('pitchxpo_react_db')) || seed; } catch { return seed; } };
const money = n => '$' + Number(n || 0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const date = s => s ? new Date(s+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'}) : '—';
const initials = name => name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();

function App(){
  const [logged,setLogged]=useState(localStorage.getItem('pitchxpo_session')==='1');
  const [page,setPage]=useState('dashboard');
  const [db,setDb]=useState(load);
  const [mobileNav,setMobileNav]=useState(false);
  const [profileOpen,setProfileOpen]=useState(false);
  const [account,setAccount]=useState(null);
  const [password,setPassword]=useState(false);
  const save=d=>{setDb(d);localStorage.setItem('pitchxpo_react_db',JSON.stringify(d));};
  const login=()=>{localStorage.setItem('pitchxpo_session','1');setLogged(true);setPage('dashboard');};
  const logout=()=>{localStorage.removeItem('pitchxpo_session');setLogged(false);setProfileOpen(false);};
  if(!logged) return <Login onLogin={login}/>;
  const nav=[['dashboard','Dashboard',LayoutDashboard],['applications','Applications',ClipboardList],['payments','Payments',WalletCards],['events','Events',CalendarDays],['types','Types & Pricing',Tags],['users','Admin Users',Users]];
  return <div className="app">
    {mobileNav && <div className="backdrop" onClick={()=>setMobileNav(false)}/>}
    <aside className={'sidebar '+(mobileNav?'open':'')}>
      <div className="brand"><img src={logo}/></div>
      <nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMobileNav(false)}}><Icon size={18}/><span>{label}</span></button>)}</nav>
      <div className="side-bottom"><b>PITCH</b><strong>PitchXPO</strong><span>Admin Panel</span></div>
    </aside>
    <main>
      <header>
        <div className="header-left"><button className="mobile-menu" onClick={()=>setMobileNav(true)} aria-label="Open menu"><Menu size={21}/></button><b>PitchXPO Admin</b></div>
        <div className="profile-wrap">
          <button className="profile-trigger" onClick={()=>setProfileOpen(v=>!v)}>
            <div className="avatar">A</div><div className="profile-text"><b>Admin User</b><span>Administrator</span></div><ChevronDown size={16} className={profileOpen?'rot':''}/>
          </button>
          {profileOpen && <div className="profile-menu">
            <button onClick={()=>{setAccount('account');setProfileOpen(false)}}><UserCircle size={17}/> My Account</button>
            <button onClick={()=>{setPassword(true);setProfileOpen(false)}}><KeyRound size={17}/> Change Password</button>
            <div className="menu-divider"/>
            <button className="logout" onClick={logout}><LogOut size={17}/> Sign out</button>
          </div>}
        </div>
      </header>
      {page==='dashboard'&&<Dashboard db={db} setPage={setPage}/>} 
      {page==='applications'&&<Applications db={db} save={save}/>} 
      {page==='payments'&&<Payments db={db}/>} 
      {page==='events'&&<Events db={db} save={save}/>} 
      {page==='types'&&<Types db={db} save={save}/>} 
      {page==='users'&&<AdminUsers db={db} save={save}/>} 
    </main>
    {account==='account'&&<Modal title="My Account" close={()=>setAccount(null)}><div className="account-card"><div className="large-avatar">A</div><div><h3>Admin User</h3><p>admin@pitchxpo.com</p><span>Super Admin</span></div></div><div className="formgrid single"><label>Full Name<input value="Admin User" readOnly/></label><label>Email<input value="admin@pitchxpo.com" readOnly/></label><label>Role<input value="Super Admin" readOnly/></label></div></Modal>}
    {password&&<ChangePassword close={()=>setPassword(false)}/>} 
  </div>;
}

function Login({onLogin}){const[email,setEmail]=useState(''),[pw,setPw]=useState(''),[show,setShow]=useState(false),[err,setErr]=useState('');return <div className="login"><div className="login-card"><img src={logo}/><h1>Welcome back</h1><p>Sign in to your PitchXPO Admin Panel</p><label>Email Address</label><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter your email" autoComplete="username"/><label>Password</label><div className="pw"><input type={show?'text':'password'} value={pw} onChange={e=>setPw(e.target.value)} placeholder="Enter your password" autoComplete="current-password"/><button onClick={()=>setShow(!show)}>{show?'Hide':'Show'}</button></div><div className="login-row"><label><input type="checkbox"/> Remember me</label><button className="link" onClick={()=>alert('Please contact the administrator to reset your password.')}>Forgot password?</button></div>{err&&<div className="error">{err}</div>}<button className="gradient login-btn" onClick={()=>email==='admin@pitchxpo.com'&&pw==='Admin@1234'?onLogin():setErr('Invalid email or password')}>Login</button><small>Demo: admin@pitchxpo.com / Admin@1234</small></div></div>}

function Page({title,sub,children,action}){return <section className="content"><div className="pagehead"><div><h1>{title}</h1><p>{sub}</p></div>{action}</div>{children}</section>}
function Cards({items}){return <div className="cards">{items.map((x,i)=><div className="card" key={i}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]||''}</small></div>)}</div>}
function Badge({children}){return <span className={'badge '+String(children).toLowerCase().replace(/\s+/g,'-')}>{children}</span>}

function Dashboard({db,setPage}){const pending=db.applications.filter(x=>['New','Reviewing'].includes(x.status)).length,approved=db.applications.filter(x=>x.status==='Approved').length,col=db.payments.filter(x=>x.status==='Paid').reduce((s,x)=>s+x.amount,0);return <Page title="Dashboard" sub="Application and payment overview" action={<button className="gradient" onClick={()=>setPage('applications')}>View Applications</button>}><Cards items={[["Total Applications",db.applications.length,'All application types'],['New / Pending',pending,'Needs review'],['Approved',approved,'Validated applications'],['Total Collected',money(col),'Successful payments']]}/><div className="grid"><div className="panel"><h3>Applications by Type <button className="text-btn" onClick={()=>setPage('applications')}>View all</button></h3>{db.types.map(t=><div className="row" key={t.id}><b>{t.name}</b><span>{db.applications.filter(a=>a.type===t.name).length}</span><span>{money(db.applications.filter(a=>a.type===t.name).reduce((s,a)=>s+a.amount,0))}</span></div>)}</div><div className="panel"><h3>Quick Status <button className="text-btn" onClick={()=>setPage('applications')}>Applications</button></h3>{['New','Reviewing','Approved','Rejected'].map(s=><div className="row" key={s}><b>{s}</b><span>{db.applications.filter(a=>a.status===s).length}</span><span>{db.applications.length?Math.round(db.applications.filter(a=>a.status===s).length/db.applications.length*100)+'%':'0%'}</span></div>)}</div></div><div className="panel tablepanel"><div className="panel-title"><h3>Recent Applications</h3><button className="text-btn" onClick={()=>setPage('applications')}>View all applications →</button></div><ApplicationTable data={db.applications.slice(0,5)}/></div></Page>}

function ApplicationTable({data,onEdit,onDelete,onView}){return <div className="tablewrap"><table><thead><tr><th>ID</th><th>Applicant / Business</th><th>Type</th><th>Event</th><th>Amount</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.map(a=><tr key={a.id}><td>{a.id}</td><td><b>{a.applicant}</b><small>{a.email}</small></td><td>{a.type}</td><td>{a.event}</td><td>{money(a.amount)}</td><td><Badge>{a.payment}</Badge></td><td><Badge>{a.status}</Badge></td><td className="actions"><button className="icon" onClick={()=>onView?onView(a):alert(a.note||'No note')} title="View"><Eye size={15}/></button>{onEdit&&<button className="icon" onClick={()=>onEdit(a)} title="Edit"><Pencil size={15}/></button>}{onDelete&&<button className="icon danger" onClick={()=>onDelete(a.id)} title="Delete"><Trash2 size={15}/></button>}</td></tr>)}</tbody></table></div>}

function Modal({title,close,children,wide=false}){return <div className="modal-layer" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className={'modal '+(wide?'wide':'')}><div className="modal-head"><div><span className="eyebrow">PITCHXPO</span><h2>{title}</h2></div><button className="close-btn" onClick={close}><X size={19}/></button></div><div className="modal-body">{children}</div></div></div>}

function Applications({db,save}){const[q,setQ]=useState(''),[status,setStatus]=useState(''),[type,setType]=useState(''),[edit,setEdit]=useState(null),[view,setView]=useState(null);const data=db.applications.filter(a=>(a.applicant+' '+a.id+' '+a.email).toLowerCase().includes(q.toLowerCase())&&(!status||a.status===status)&&(!type||a.type===type));const saveApp=(a,form)=>{const o={...a,id:a.id||'PX-'+Date.now().toString().slice(-5),applicant:form.applicant,email:form.email,phone:form.phone,type:form.type,event:form.event,amount:Number(form.amount),status:form.status,payment:form.payment,note:form.note,date:a.date||new Date().toISOString().slice(0,10),documents:a.documents||[]};save({...db,applications:a.id?db.applications.map(x=>x.id===a.id?o:x):[o,...db.applications]});setEdit(null)};return <Page title="Applications" sub="Review, update and manage all applications" action={<button className="gradient" onClick={()=>setEdit({})}><Plus size={16}/> Add Application</button>}><div className="panel"><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Search applicant, ID or email" value={q} onChange={e=>setQ(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All status</option><option>New</option><option>Reviewing</option><option>Approved</option><option>Rejected</option></select><select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{db.types.map(t=><option key={t.id}>{t.name}</option>)}</select></div><ApplicationTable data={data} onView={setView} onEdit={setEdit} onDelete={id=>confirm('Delete application?')&&save({...db,applications:db.applications.filter(x=>x.id!==id)})}/></div>{edit!==null&&<ApplicationModal value={edit} db={db} close={()=>setEdit(null)} onSave={saveApp}/>} {view&&<Modal title={view.id} close={()=>setView(null)} wide><div className="detail-grid"><div><span>Applicant / Business</span><b>{view.applicant}</b></div><div><span>Email</span><b>{view.email}</b></div><div><span>Phone</span><b>{view.phone||'—'}</b></div><div><span>Event</span><b>{view.event}</b></div><div><span>Type</span><b>{view.type}</b></div><div><span>Amount</span><b>{money(view.amount)}</b></div><div><span>Payment</span><Badge>{view.payment}</Badge></div><div><span>Status</span><Badge>{view.status}</Badge></div></div><div className="detail-note"><b>Admin Note</b><p>{view.note||'No note added.'}</p></div><div className="documents"><b>Documents</b>{(view.documents||[]).map(d=><button key={d} className="doc-btn" onClick={()=>alert('Document download: '+d)}><Download size={14}/>{d}</button>)}</div></Modal>}</Page>}

function ApplicationModal({value,db,close,onSave}){const[v,setV]=useState({applicant:'',email:'',phone:'',type:db.types[0]?.name||'Raise Funds',event:db.events[0]?.name||'PitchXPO Conclave',amount:99,payment:'Paid',status:'New',note:'',...value});const set=(k,x)=>setV({...v,[k]:x});return <Modal title={value.id||'New Application'} close={close} wide><div className="formgrid"><label>Applicant / Business<input value={v.applicant} onChange={e=>set('applicant',e.target.value)}/></label><label>Email<input value={v.email} onChange={e=>set('email',e.target.value)}/></label><label>Phone<input value={v.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Event<select value={v.event} onChange={e=>set('event',e.target.value)}>{db.events.map(e=><option key={e.id}>{e.name}</option>)}</select></label><label>Type<select value={v.type} onChange={e=>set('type',e.target.value)}>{db.types.map(t=><option key={t.id}>{t.name}</option>)}</select></label><label>Amount (USD)<input type="number" min="0" value={v.amount} onChange={e=>set('amount',e.target.value)}/></label><label>Payment<select value={v.payment} onChange={e=>set('payment',e.target.value)}><option>Paid</option><option>Unpaid</option></select></label><label>Status<select value={v.status} onChange={e=>set('status',e.target.value)}><option>New</option><option>Reviewing</option><option>Approved</option><option>Rejected</option></select></label><label className="full">Admin Note<textarea value={v.note} onChange={e=>set('note',e.target.value)}/></label></div><div className="modal-actions"><button className="btn" onClick={close}>Cancel</button><button className="gradient" onClick={()=>onSave(value,v)}>Save Application</button></div></Modal>}

function Payments({db}){const[q,setQ]=useState(''),[s,setS]=useState('');const data=db.payments.filter(x=>(x.applicant+' '+x.reference+' '+x.application).toLowerCase().includes(q.toLowerCase())&&(!s||x.status===s));const paid=db.payments.filter(x=>x.status==='Paid');return <Page title="Payments" sub="Track paid and unpaid application payments" action={<button className="btn" onClick={()=>download('pitchxpo-payments.csv',db.payments)}> <Download size={15}/> Download Excel</button>}><Cards items={[["Paid Amount",money(paid.reduce((s,x)=>s+x.amount,0)),'Successful payments'],['Paid',paid.length,'Transactions'],['Unpaid',db.payments.filter(x=>x.status==='Unpaid').length,'Pending payment'],['Outstanding',money(db.payments.filter(x=>x.status==='Unpaid').reduce((s,x)=>s+x.amount,0)),'Due amount']]}/><div className="panel tablepanel"><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Search applicant or reference" value={q} onChange={e=>setQ(e.target.value)}/></div><select value={s} onChange={e=>setS(e.target.value)}><option value="">All payments</option><option>Paid</option><option>Unpaid</option></select></div><div className="tablewrap"><table><thead><tr><th>ID</th><th>Application</th><th>Applicant</th><th>Type</th><th>Amount</th><th>Status</th><th>Payment Reference</th><th>Date</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.application}</td><td><b>{x.applicant}</b></td><td>{x.type}</td><td>{money(x.amount)}</td><td><Badge>{x.status}</Badge></td><td>{x.reference}</td><td>{date(x.date)}</td></tr>)}</tbody></table></div></div></Page>}

function Events({db,save}){const[edit,setEdit]=useState(null);return <Page title="Events" sub="Create and manage events with date ranges" action={<button className="gradient" onClick={()=>setEdit({})}><Plus size={16}/> Add Event</button>}><div className="panel"><div className="tablewrap"><table><thead><tr><th>Event</th><th>From Date</th><th>To Date</th><th>Venue</th><th>Status</th><th>Actions</th></tr></thead><tbody>{db.events.map(e=><tr key={e.id}><td><b>{e.name}</b></td><td>{date(e.from)}</td><td>{date(e.to)}</td><td>{e.venue}</td><td><Badge>{e.status}</Badge></td><td className="actions"><button className="icon" onClick={()=>setEdit(e)}><Pencil size={15}/></button><button className="icon danger" onClick={()=>confirm('Delete event?')&&save({...db,events:db.events.filter(x=>x.id!==e.id)})}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div></div>{edit!==null&&<EventModal value={edit} close={()=>setEdit(null)} save={o=>{save({...db,events:edit.id?db.events.map(x=>x.id===edit.id?o:x):[o,...db.events]});setEdit(null)}}/>}</Page>}
function EventModal({value,close,save}){const[v,setV]=useState({name:'',venue:'',from:'',to:'',status:'Open',...value});return <Modal title={value.id?'Edit Event':'Add Event'} close={close}><div className="formgrid"><label>Event Name<input value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Venue<input value={v.venue} onChange={e=>setV({...v,venue:e.target.value})}/></label><label>From Date<input type="date" value={v.from} onChange={e=>setV({...v,from:e.target.value})}/></label><label>To Date<input type="date" value={v.to} onChange={e=>setV({...v,to:e.target.value})}/></label></div><div className="modal-actions"><button className="btn" onClick={close}>Cancel</button><button className="gradient" onClick={()=>{if(!v.name||!v.from||!v.to)return alert('Please complete event details.');if(v.to<v.from)return alert('To Date cannot be before From Date.');save({...v,id:v.id||'EV-'+Date.now().toString().slice(-5)})}}>Save Event</button></div></Modal>}

function Types({db,save}){const[edit,setEdit]=useState(null);return <Page title="Types & Pricing" sub="Manage application categories and USD pricing" action={<button className="gradient" onClick={()=>setEdit({})}><Plus size={16}/> Add Type</button>}><div className="type-grid">{db.types.map(t=><div className="type-card" key={t.id}><div className="type-top"><span>{t.active?'Active':'Disabled'}</span><Badge>{money(t.price)}</Badge></div><h3>{t.name}</h3><p>{t.description||'No description added.'}</p><div className="type-actions"><button className="btn" onClick={()=>setEdit(t)}><Pencil size={14}/> Edit</button><button className="btn" onClick={()=>save({...db,types:db.types.map(x=>x.id===t.id?{...x,active:!x.active}:x)})}>{t.active?'Disable':'Enable'}</button></div></div>)}</div>{edit!==null&&<TypeModal value={edit} close={()=>setEdit(null)} save={o=>{save({...db,types:edit.id?db.types.map(x=>x.id===edit.id?o:x):[...db.types,o]});setEdit(null)}}/>}</Page>}
function TypeModal({value,close,save}){const[v,setV]=useState({name:'',description:'',price:99,active:true,...value});return <Modal title={value.id?'Edit Type':'Add Type'} close={close}><div className="formgrid"><label>Name<input value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Price (USD)<input type="number" min="0" value={v.price} onChange={e=>setV({...v,price:e.target.value})}/></label><label className="full">Description<textarea value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></label></div><div className="modal-actions"><button className="btn" onClick={close}>Cancel</button><button className="gradient" onClick={()=>save({...v,id:v.id||'TP-'+Date.now()})}>Save Type</button></div></Modal>}

function AdminUsers({db,save}){const[edit,setEdit]=useState(null);return <Page title="Admin Users" sub="Manage administrator access" action={<button className="gradient" onClick={()=>setEdit({})}><Plus size={16}/> Add Admin</button>}><div className="panel"><div className="tablewrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{db.users.map(u=><tr key={u.id}><td><b>{u.name}</b></td><td>{u.email}</td><td>{u.role}</td><td><Badge>{u.status}</Badge></td><td className="actions"><button className="icon" onClick={()=>setEdit(u)}><Pencil size={15}/></button><button className="text-action" onClick={()=>save({...db,users:db.users.map(x=>x.id===u.id?{...x,status:x.status==='Active'?'Inactive':'Active'}:x)})}>{u.status==='Active'?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div></div>{edit!==null&&<UserModal value={edit} close={()=>setEdit(null)} save={o=>{save({...db,users:edit.id?db.users.map(x=>x.id===edit.id?o:x):[...db.users,o]});setEdit(null)}}/>}</Page>}
function UserModal({value,close,save}){const[v,setV]=useState({name:'',email:'',role:'Reviewer',status:'Active',...value});return <Modal title={value.id?'Edit Admin':'Add Admin'} close={close}><div className="formgrid"><label>Name<input value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><label>Email<input type="email" value={v.email} onChange={e=>setV({...v,email:e.target.value})}/></label><label>Role<select value={v.role} onChange={e=>setV({...v,role:e.target.value})}><option>Super Admin</option><option>Reviewer</option></select></label><label>Status<select value={v.status} onChange={e=>setV({...v,status:e.target.value})}><option>Active</option><option>Inactive</option></select></label></div><div className="modal-actions"><button className="btn" onClick={close}>Cancel</button><button className="gradient" onClick={()=>save({...v,id:v.id||'USR-'+Date.now()})}>Save Admin</button></div></Modal>}

function ChangePassword({close}){const[a,setA]=useState(''),[b,setB]=useState(''),[c,setC]=useState('');return <Modal title="Change Password" close={close}><div className="formgrid single"><label>Current Password<input type="password" value={a} onChange={e=>setA(e.target.value)}/></label><label>New Password<input type="password" value={b} onChange={e=>setB(e.target.value)}/></label><label>Confirm New Password<input type="password" value={c} onChange={e=>setC(e.target.value)}/></label></div><div className="modal-actions"><button className="btn" onClick={close}>Cancel</button><button className="gradient" onClick={()=>{if(!a||!b||b!==c)return alert('Please check the password fields.');alert('Password changed successfully.');close()}}>Update Password</button></div></Modal>}

function download(name,rows){const keys=Object.keys(rows[0]||{});const csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}

createRoot(document.getElementById('root')).render(<App/>);
