import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {LayoutDashboard,ClipboardList,WalletCards,CalendarDays,Tags,UsersRound,LogOut,Search,Plus,Download,Eye,Pencil,Trash2,Check,X,Menu,ChevronDown,LockKeyhole,UserCircle,Settings,FileText} from "lucide-react";
import "./theme.css";

const seed={
 applications:[
  {id:"PX-10248",applicant:"ABC Technologies",email:"hello@abctech.com",phone:"+91 98765 12001",type:"Raise Funds",event:"PitchXPO Conclave",amount:99,payment:"Paid",status:"New",date:"2026-08-18",note:"",documents:["Pitch Deck.pdf","Company Profile.pdf"]},
  {id:"PX-10247",applicant:"Nova Properties",email:"contact@novaproperties.com",phone:"+91 98765 12002",type:"Showcase",event:"PitchXPO Conclave",amount:99,payment:"Paid",status:"Reviewing",date:"2026-08-17",note:"Financial documents need review.",documents:["Company Profile.pdf"]},
  {id:"PX-10246",applicant:"Northstar Capital",email:"team@northstar.com",phone:"+91 98765 12003",type:"Investor Success Story",event:"PitchXPO Conclave",amount:299,payment:"Paid",status:"Approved",date:"2026-08-16",note:"Approved by admin.",documents:["Success Story.pdf","Logo.png"]},
  {id:"PX-10245",applicant:"Vertex Labs",email:"founders@vertexlabs.com",phone:"+91 98765 12004",type:"Raise Funds",event:"PitchXPO Conclave",amount:99,payment:"Unpaid",status:"New",date:"2026-08-15",note:"",documents:["Pitch Deck.pdf"]},
  {id:"PX-10244",applicant:"GreenGrid Energy",email:"admin@greengrid.co",phone:"+1 212 555 0198",type:"Showcase",event:"PitchXPO Conclave",amount:149,eventStatus:"Active",payment:"Paid",status:"Approved",date:"2026-08-14",note:"",documents:["Company Profile.pdf"]}
 ],
 events:[
  {id:"EV-001",name:"PitchXPO Conclave",location:"Dubai",from:"2026-10-15",to:"2026-10-17",status:"Active"},
  {id:"EV-002",name:"PitchXPO Showcase",location:"Abu Dhabi",from:"2026-11-05",to:"2026-11-06",status:"Upcoming"}
 ],
 types:[
  {id:"TP-001",name:"Raise Funds",price:99,status:"Active"},
  {id:"TP-002",name:"Showcase",price:149,status:"Active"},
  {id:"TP-003",name:"Investor Success Story",price:299,status:"Active"}
 ],
 admins:[{id:"AD-001",name:"Admin User",email:"admin@pitchxpo.com",role:"Super Admin",status:"Active"}]
};

function load(k){try{return JSON.parse(localStorage.getItem("px_"+k))||seed[k]}catch{return seed[k]}}
function save(k,v){localStorage.setItem("px_"+k,JSON.stringify(v))}
const money=n=>`$${Number(n||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const badge=s=><span className={"badge "+String(s).toLowerCase().replace(/\s/g,"")}>{s}</span>;

function Login({onLogin}) {
 const [email,setEmail]=useState(""),[pass,setPass]=useState(""),[show,setShow]=useState(false),[error,setError]=useState("");
 const submit=e=>{e.preventDefault();const saved=localStorage.getItem("px_password")||"Admin@1234";if(email.toLowerCase()==="admin@pitchxpo.com"&&pass===saved){localStorage.setItem("px_session","1");onLogin()}else setError("Invalid email or password.")};
 return <div className="login-page"><div className="login-shell">
  <section className="login-brand-side"><img src="/src/assets/pitch-logo.png" alt="Pitch"/><h2>PitchXPO Admin Portal</h2><p>Manage applications, events, payments and administration from one simple workspace.</p><div className="login-points"><div className="login-point"><span>✓</span>Application review & approval</div><div className="login-point"><span>✓</span>Events, dates & pricing</div><div className="login-point"><span>✓</span>Payments & admin users</div></div></section>
  <section className="login-form-side"><div className="eyebrow">Secure access</div><h1>Welcome back</h1><div className="login-sub">Sign in to continue to your PitchXPO Admin Panel.</div>{error&&<div className="login-error show">{error}</div>}
  <form className="login-form" onSubmit={submit}><div className="field"><label>Email Address</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@pitchxpo.com" required/></div>
  <div className="field"><label>Password</label><div className="password-wrap"><input className="input" type={show?"text":"password"} value={pass} onChange={e=>setPass(e.target.value)} placeholder="Enter your password" required/><button type="button" className="show-pass" onClick={()=>setShow(!show)}>{show?"Hide":"Show"}</button></div></div>
  <div className="login-options"><label><input type="checkbox"/> Remember me</label><button type="button" className="text-link" onClick={()=>alert("Password reset flow: enter your registered email. Demo code: 123456.")}>Forgot password?</button></div>
  <button className="primary login-submit">Sign In</button></form><div className="demo-login"><strong>Demo login</strong><br/>Email: admin@pitchxpo.com &nbsp; | &nbsp; Password: Admin@1234</div><div className="login-footer">PitchXPO Admin Panel · Secure administrator access</div></section>
 </div></div>
}

function App(){
 const [logged,setLogged]=useState(localStorage.getItem("px_session")==="1");
 const [page,setPage]=useState("dashboard"),[mobile,setMobile]=useState(false);
 const [apps,setApps]=useState(load("applications")),[events,setEvents]=useState(load("events")),[types,setTypes]=useState(load("types")),[admins,setAdmins]=useState(load("admins"));
 const [modal,setModal]=useState(null);
 useEffect(()=>save("applications",apps),[apps]);useEffect(()=>save("events",events),[events]);useEffect(()=>save("types",types),[types]);useEffect(()=>save("admins",admins),[admins]);
 if(!logged)return <Login onLogin={()=>setLogged(true)}/>;
 const logout=()=>{localStorage.removeItem("px_session");setLogged(false);setPage("dashboard")};
 const nav=[["dashboard",LayoutDashboard,"Dashboard"],["applications",ClipboardList,"Applications"],["payments",WalletCards,"Payments"],["events",CalendarDays,"Events"],["types",Tags,"Types & Pricing"],["admins",UsersRound,"Admin Users"]];
 return <div className="shell"><aside className={"sidebar "+(mobile?"open":"")}><div className="brand"><img src="/src/assets/pitch-logo.png"/></div><nav className="menu">{nav.map(([p,I,t])=><button key={p} className={"menu-btn "+(page===p?"active":"")} onClick={()=>{setPage(p);setMobile(false)}}><I size={18}/>{t}</button>)}</nav><div className="sidebar-bottom"><div className="side-line"/><div className="mini-brand"><span className="mini-pitch">PITCH</span><div><b>PitchXPO</b><small>Admin Panel</small></div></div></div></aside>
 <main className="main"><header className="topbar"><div className="top-left"><button className="mobile-menu" onClick={()=>setMobile(!mobile)}><Menu size={18}/></button><b>PitchXPO Admin</b></div><div className="profile"><div className="avatar">A</div><div><b>Admin User</b><small>Administrator</small></div><button className="profile-drop" onClick={logout}><LogOut size={15}/> Sign out</button></div></header>
 <section>{page==="dashboard"?<Dashboard apps={apps}/>:page==="applications"?<Applications apps={apps} setApps={setApps} setModal={setModal}/>:page==="payments"?<Payments apps={apps} setApps={setApps}/>:page==="events"?<Events events={events} setEvents={setEvents}/>:page==="types"?<Types types={types} setTypes={setTypes}/>:<Admins admins={admins} setAdmins={setAdmins}/>}</section></main>
 {modal&&<ApplicationModal a={modal} apps={apps} setApps={setApps} close={()=>setModal(null)}/>}
 </div>
}

const Head=({title,sub,action})=><div className="page-head"><div><h1>{title}</h1><p>{sub}</p></div>{action}</div>;
function Dashboard({apps}){const total=248+Math.max(0,apps.length-5),approved=186+apps.filter(a=>a.status==="Approved").length-2,pending=32+apps.filter(a=>["New","Reviewing"].includes(a.status)).length-3;const collected=28450+apps.reduce((s,a)=>s+(a.payment==="Paid"?a.amount:0),0)-646;return <><Head title="Dashboard" sub="Application and payment overview" action={<button className="primary" onClick={()=>location.hash="applications"}>View Applications</button>}/><div className="cards"><Card t="Total Applications" v={total} n="All application types"/><Card t="New / Pending" v={pending} n={<><span className="purple-dot"/>Needs review</>}/><Card t="Approved" v={approved} n="Validated applications"/><Card t="Total Collected" v={money(collected)} n="Successful payments"/></div><div className="dashboard-grid"><div className="panel"><div className="panel-head"><h3>Applications by Type</h3></div>{["Raise Funds","Showcase","Investor Success Story"].map((x,i)=><div className="simple-row" key={x}><b>{x}</b><span>{[120,95,33][i]}</span><span>{["$11,880.00","$9,405.00","$7,165.00"][i]}</span></div>)}</div><div className="panel"><div className="panel-head"><h3>Quick Status</h3></div>{[["New",18,"7.3%"],["Under Review",14,"5.6%"],["Approved",186,"75%"],["Rejected",30,"12.1%"]].map(x=><div className="status-row" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><span>{x[2]}</span></div>)}</div></div><div className="panel table-panel"><div className="panel-head"><h3>Recent Applications</h3></div><AppTable data={apps.slice(0,4)}/></div></>}
function Card({t,v,n}){return <div className="card"><small>{t}</small><h2>{v}</h2><div className="card-note">{n}</div></div>}

function AppTable({data,onView}){return <div className="table-wrap"><table className="table"><thead><tr><th>ID</th><th>Applicant / Business</th><th>Type</th><th>Event</th><th>Amount</th><th>Payment</th><th>Status</th><th></th></tr></thead><tbody>{data.map(a=><tr key={a.id}><td>{a.id}</td><td><b>{a.applicant}</b></td><td>{a.type}</td><td>{a.event}</td><td>{money(a.amount)}</td><td className={a.payment.toLowerCase()}>{a.payment}</td><td>{badge(a.status)}</td><td><button className="view" onClick={()=>onView&&onView(a)}>View</button></td></tr>)}</tbody></table></div>}

function Applications({apps,setApps,setModal}){const [q,setQ]=useState(""),[s,setS]=useState(""),[t,setT]=useState("");const data=apps.filter(a=>(a.id+" "+a.applicant).toLowerCase().includes(q.toLowerCase())&&(!s||a.status===s)&&(!t||a.type===t));const add=()=>setModal({new:true});return <><Head title="Applications" sub="Manage submitted applications" action={<button className="primary" onClick={add}><Plus size={15}/> Add Application</button>}/><div className="panel"><div className="toolbar"><div className="searchbox"><Search size={15}/><input placeholder="Search applicant or ID" value={q} onChange={e=>setQ(e.target.value)}/></div><select className="field" value={s} onChange={e=>setS(e.target.value)}><option value="">All status</option><option>New</option><option>Reviewing</option><option>Approved</option><option>Rejected</option></select><select className="field" value={t} onChange={e=>setT(e.target.value)}><option value="">All types</option>{typesList(apps).map(x=><option key={x}>{x}</option>)}</select></div><AppTable data={data} onView={setModal}/></div></>}
function typesList(a){return [...new Set(a.map(x=>x.type))]}
function ApplicationModal({a,apps,setApps,close}){const [form,setForm]=useState(a.new?{id:"PX-"+(10249+apps.length),applicant:"",email:"",phone:"",type:"Raise Funds",event:"PitchXPO Conclave",amount:99,payment:"Unpaid",status:"New",date:new Date().toISOString().slice(0,10),note:"",documents:[]}:a);const update=(k,v)=>setForm({...form,[k]:v});const saveIt=()=>{if(a.new)setApps([...apps,form]);else setApps(apps.map(x=>x.id===form.id?form:x));close()};return <div className="modal"><div className="modal-card"><div className="modal-head"><div><small>{a.new?"NEW APPLICATION":"APPLICATION"}</small><h3>{a.new?"Add Application":form.id}</h3></div><button onClick={close}>×</button></div><div className="form-grid">{[["Applicant / Business","applicant"],["Email","email"],["Phone","phone"],["Event","event"]].map(([l,k])=><div className="field-block" key={k}><label>{l}</label><input className="input" value={form[k]} onChange={e=>update(k,e.target.value)}/></div>)}<div className="field-block"><label>Type</label><select className="input" value={form.type} onChange={e=>update("type",e.target.value)}><option>Raise Funds</option><option>Showcase</option><option>Investor Success Story</option></select></div><div className="field-block"><label>Amount (USD)</label><input className="input" type="number" value={form.amount} onChange={e=>update("amount",e.target.value)}/></div><div className="field-block"><label>Payment</label><select className="input" value={form.payment} onChange={e=>update("payment",e.target.value)}><option>Paid</option><option>Unpaid</option></select></div><div className="field-block"><label>Status</label><select className="input" value={form.status} onChange={e=>update("status",e.target.value)}><option>New</option><option>Reviewing</option><option>Approved</option><option>Rejected</option></select></div></div><div className="field-block" style={{marginTop:12}}><label>Admin Note</label><textarea className="input" value={form.note} onChange={e=>update("note",e.target.value)}/></div><div className="modal-actions"><button className="btn" onClick={close}>Cancel</button><button className="primary" onClick={saveIt}>Save Application</button></div></div></div>}

function Payments({apps,setApps}){const [q,setQ]=useState("");const data=apps.filter(a=>(a.id+" "+a.applicant+" "+a.payment).toLowerCase().includes(q.toLowerCase()));return <><Head title="Payments" sub="Track successful and pending payments" action={<button className="primary" onClick={()=>alert("Export prepared in the full backend version.")}><Download size={15}/> Download Excel</button>}/><div className="panel"><div className="toolbar"><div className="searchbox"><Search size={15}/><input placeholder="Search applicant or ID" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Application</th><th>Applicant</th><th>Amount</th><th>Payment</th><th>Reference</th><th>Date</th><th></th></tr></thead><tbody>{data.map(a=><tr key={a.id}><td>{a.id}</td><td><b>{a.applicant}</b></td><td>{money(a.amount)}</td><td className={a.payment.toLowerCase()}>{a.payment}</td><td>PAY-{a.id.slice(-5)}</td><td>{a.date}</td><td><button className="view" onClick={()=>setApps(apps.map(x=>x.id===a.id?{...x,payment:x.payment==="Paid"?"Unpaid":"Paid"}:x))}>{a.payment==="Paid"?"Mark Unpaid":"Mark Paid"}</button></td></tr>)}</tbody></table></div></div></>}

function Events({events,setEvents}){const [editing,setEditing]=useState(null);const blank={id:"EV-"+String(events.length+1).padStart(3,"0"),name:"",location:"",from:"",to:"",status:"Upcoming"};const [f,setF]=useState(blank);const open=e=>{setF(e||{...blank,id:"EV-"+String(events.length+1).padStart(3,"0")});setEditing(true)};const saveIt=()=>{if(!f.from||!f.to||f.to<f.from){alert("To Date must be the same as or after From Date.");return}setEvents(events.some(x=>x.id===f.id)?events.map(x=>x.id===f.id?f:x):[...events,f]);setEditing(null)};return <><Head title="Events" sub="Manage events with From and To dates" action={<button className="primary" onClick={()=>open()}><Plus size={15}/> Add Event</button>}/><div className="panel"><div className="table-wrap"><table className="table"><thead><tr><th>Event</th><th>Location</th><th>From Date</th><th>To Date</th><th>Status</th><th></th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td><b>{e.name}</b></td><td>{e.location}</td><td>{e.from}</td><td>{e.to}</td><td>{badge(e.status)}</td><td><button className="icon-btn" onClick={()=>open(e)}><Pencil size={14}/></button><button className="icon-btn danger" onClick={()=>setEvents(events.filter(x=>x.id!==e.id))}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div></div>{editing&&<div className="modal"><div className="modal-card"><div className="modal-head"><div><small>EVENT</small><h3>{f.name||"Add Event"}</h3></div><button onClick={()=>setEditing(null)}>×</button></div><div className="form-grid"><div className="field-block"><label>Event Name</label><input className="input" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></div><div className="field-block"><label>Location</label><input className="input" value={f.location} onChange={e=>setF({...f,location:e.target.value})}/></div><div className="field-block"><label>From Date</label><input className="input" type="date" value={f.from} onChange={e=>setF({...f,from:e.target.value})}/></div><div className="field-block"><label>To Date</label><input className="input" type="date" value={f.to} onChange={e=>setF({...f,to:e.target.value})}/></div></div><div className="modal-actions"><button className="btn" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" onClick={saveIt}>Save Event</button></div></div></div>}</>}

function Types({types,setTypes}){const [f,setF]=useState(null);const blank={id:"TP-"+String(types.length+1).padStart(3,"0"),name:"",price:99,status:"Active"};const saveIt=()=>{setTypes(types.some(x=>x.id===f.id)?types.map(x=>x.id===f.id?f:x):[...types,f]);setF(null)};return <><Head title="Types & Pricing" sub="Manage application categories and USD pricing" action={<button className="primary" onClick={()=>setF(blank)}><Plus size={15}/> Add Type</button>}/><div className="panel">{types.map(t=><div className="tag" key={t.id}><div><b>{t.name}</b><small>{money(t.price)}</small></div><div><button className="icon-btn" onClick={()=>setF(t)}><Pencil size={14}/></button><button className="view" onClick={()=>setTypes(types.map(x=>x.id===t.id?{...x,status:x.status==="Active"?"Disabled":"Active"}:x))}>{t.status}</button><button className="icon-btn danger" onClick={()=>setTypes(types.filter(x=>x.id!==t.id))}><Trash2 size={14}/></button></div></div>)}</div>{f&&<div className="modal"><div className="modal-card"><div className="modal-head"><div><small>APPLICATION CATEGORY</small><h3>{f.name||"Add Type"}</h3></div><button onClick={()=>setF(null)}>×</button></div><div className="form-grid"><div className="field-block"><label>Name</label><input className="input" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></div><div className="field-block"><label>Price (USD)</label><input className="input" type="number" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/></div></div><div className="modal-actions"><button className="btn" onClick={()=>setF(null)}>Cancel</button><button className="primary" onClick={saveIt}>Save</button></div></div></div>}</>}

function Admins({admins,setAdmins}){const [f,setF]=useState(null);const blank={id:"AD-"+String(admins.length+1).padStart(3,"0"),name:"",email:"",role:"Admin",status:"Active"};const saveIt=()=>{setAdmins(admins.some(x=>x.id===f.id)?admins.map(x=>x.id===f.id?f:x):[...admins,f]);setF(null)};return <><Head title="Admin Users" sub="Manage administrator access" action={<button className="primary" onClick={()=>setF(blank)}><Plus size={15}/> Add Admin</button>}/><div className="panel"><div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>{admins.map(a=><tr key={a.id}><td><b>{a.name}</b></td><td>{a.email}</td><td>{a.role}</td><td>{badge(a.status)}</td><td><button className="icon-btn" onClick={()=>setF(a)}><Pencil size={14}/></button><button className="view" onClick={()=>setAdmins(admins.map(x=>x.id===a.id?{...x,status:x.status==="Active"?"Disabled":"Active"}:x))}>{a.status==="Active"?"Disable":"Enable"}</button></td></tr>)}</tbody></table></div></div>{f&&<div className="modal"><div className="modal-card"><div className="modal-head"><div><small>ADMIN USER</small><h3>{f.name||"Add Admin"}</h3></div><button onClick={()=>setF(null)}>×</button></div><div className="form-grid"><div className="field-block"><label>Name</label><input className="input" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></div><div className="field-block"><label>Email</label><input className="input" type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></div><div className="field-block"><label>Role</label><select className="input" value={f.role} onChange={e=>setF({...f,role:e.target.value})}><option>Super Admin</option><option>Admin</option><option>Finance Admin</option><option>Event Manager</option></select></div></div><div className="modal-actions"><button className="btn" onClick={()=>setF(null)}>Cancel</button><button className="primary" onClick={saveIt}>Save Admin</button></div></div></div>}</>}

createRoot(document.getElementById("root")).render(<App/>);
